### ISSUE TITLE
Rebuild .darknode directory

### ISSUE THREAD

**Issue by spoon2eric** [renproject/darknode-cli#35]
To connect back to the already deployed and running darknode (running and fully funded)..

What are the recovery steps for a user to freshly re-build / configure the .darknode folder if it is lost or deleted? SSH URLs and connection files + details about the darknodes should be recovered in some way if the user loses this .darknode folder.

Again, this is assuming the user has already deployed the darknode and later accidentally lost the critical folder to allow the user to connect back to the darknode.

**Comment by spoon2eric** [comment]
My understanding is that:
1. You can still de-register the darknode using the Command Center
2. You can still "refund" the 100k REN using the Command Center
3. You CANNOT withdraw rewards or GAS without the CLI on the local machine

Is it possible to login to the VM host provider, reset the root password, reboot the VM and then gain access to the CLI to "correctly" de-register/refund/destroy the darknode?

What options are there for people that lose this local folder and did not back up this .darknode directory? Is there a way to download or regain access to all the files needed? Potentially re-install the CLI and manually create or restore "from scratch" the files required for the .darknode directory when you already have a running and "registered" REN Darknode?

**Comment by Pega88** [comment]
since a darknode is setup using terraform locally, an idea might be to backup this directory after generation on the blob storage solution as a last step terraform provides in the creation of the darknode? e.g. S3 in case of AWS deployment, or GCS in case of GCP deployment?

**Comment by loongy** [comment]
We can definitely add a backup option to the CLI but I don’t think it’s a good idea to back it up remotely, because this introduces yet another vector for attack.

A backup would be password encrypted and zipped up. The user could then copy that somewhere for safe keeping.

Another alternative we have been thinking about is removing SSH access altogether. Instead, an ECDSA signature (matching that of the owner) could be used to issue commands to the Darknode via its JSON-RPC 2.0 interface. This removes the need for backups altogether and locks down access to the Darknodes, making it much more secure.

**Comment by loongy** [comment]
> Is it possible to login to the VM host provider, reset the root password, reboot the VM and then gain access to the CLI to "correctly" de-register/refund/destroy the darknode?

No. This isn’t possible. Cloud providers don’t keep copies of access keys to your machines. If the SSH key is lost, there is no way to recover it and the only option is to shutdown the Darknode.

**Comment by Pega88** [comment]
I guess in an ideal world, the darknode private key/ eth address could be managed from a Ledger rather than by the darknode creation process? or does the darknode itself stores a copy of the private key?

**Comment by loongy** [comment]
That’s impossible, because the Darknode needs to use this key automatically (and the point of a Ledger is to require a human to click that button). But this key is not the issue.

The SSH key is how you access the Darknode to deploy updates. Without it, you need to shutdown the Darknode, de-register, and start again (otherwise, your Darknode will fall out-of-date). The only way around this is to (a) back up the key, or (b) remove the need for it.

**Comment by Pega88** [comment]
makes sense. As long as you manage the cloud environment, you should have access to the VMs hosted there.

There might be minimal instances of when someone else provides you with the keys/auth, but as long as those keys are valid, you'll always have raw access to the VMs. For Google, [$gcloud](https://cloud.google.com/sdk/gcloud/reference/compute/ssh) CLI can manage new ssh key propagation to the VM from any authenticated terminal
