### ISSUE TITLE
darknode DO-setup fails

### ISSUE THREAD

**Issue by FelipeNystrom** [renproject/darknode-cli#38]
I'm trying to set up a darknode with the latest cli but have runned in a problem. 

I have an access key setup on DO and when I follow the [instructions](https://renproject.zendesk.com/hc/en-us/articles/360015368973-How-to-Setup-a-Darknode-Mainnet-Instructions-Digital-Ocean) for setting up a darknode on DO and run 

```darknode up --name {darknodename} --do --do-token {do-api-token}```

the process exits with the following output:

```
digitalocean_droplet.darknode (remote-exec): + get_latest_release linux-amd64
digitalocean_droplet.darknode (remote-exec): + + wget -qi -
digitalocean_droplet.darknode (remote-exec): tr -d "
digitalocean_droplet.darknode (remote-exec): + cut -d : -f 2,3
digitalocean_droplet.darknode (remote-exec): + grep browser_download_url.*darknode-linux-amd64.zip
digitalocean_droplet.darknode (remote-exec): + curl -s https://api.github.com/repos/republicprotocol/darknode-cli/releases/latest
digitalocean_droplet.darknode (remote-exec): + mv darknode-linux-amd64.zip darknode.zip
digitalocean_droplet.darknode (remote-exec): mv: cannot stat 'darknode-linux-amd64.zip': No such file or directory
digitalocean_droplet.darknode (remote-exec): + unzip darknode.zip
digitalocean_droplet.darknode (remote-exec): unzip:  cannot find or open darknode.zip, darknode.zip.zip or darknode.zip.ZIP.
digitalocean_droplet.darknode (remote-exec): + mkdir -p ./.darknode
digitalocean_droplet.darknode (remote-exec): + mv ./darknode-config.json ./.darknode/config.json
digitalocean_droplet.darknode (remote-exec): + cd darknode
digitalocean_droplet.darknode (remote-exec): /tmp/terraform_1510456658.sh: 21: cd: can't cd to darknode
digitalocean_droplet.darknode (remote-exec): + chmod +x install.sh

Error: Error applying plan:

1 error(s) occurred:

* digitalocean_droplet.darknode: error executing "/tmp/terraform_1510456658.sh": Process exited with status 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


exit status 1
```

I'm on arch linux with manjaro 18.1 if it matters.

Greatful for any help

**Comment by tok-kkk** [comment]
Thanks, @FelipeNystrom for reporting the issue. We have pushed a fix for this and you need to update your darknode with the command `curl https://releases.republicprotocol.com/darknode-cli/update.sh -sSf | sh`.

Please noted the failure happens when trying to set up darknode service on digital ocean instance which means the instance has been created and running. You need to login your digital ocean account and manually destroy the instance from the browser. After that, just in case, delete the `$HOME/.darknode/darknodes/DARKNODE-NAME` folder before trying to deploy a new node.

Let me know if that fixes your issue.

**Comment by FelipeNystrom** [comment]
The update solved my issue! Thank you! :D
