### ISSUE TITLE
Missing AWS Regions

### ISSUE THREAD

**Issue by fanaticalfishing** [renproject/darknode-cli#73]
There are AWS Regions missing from
https://github.com/renproject/darknode-cli/blob/master/cmd/provider/aws.go

af-south-1 
ap-east-1
ap-northeast-3
cn-north-1
cn-northwest-1
eu-south-1
me-south-1

**Comment by tok-kkk** [comment]
Hi @fanaticalfishing, thanks for pointing this out. 
The current implementation hardcodes all the AWS regions and excludes the regions which need manual activation to use.  We try to avoid selecting a region (when user not specifies) that unavailable to the user.
Having said that, we already start to improve this. In the next coming release, instead of hardcoding all regions, cli will query AWS API and verify if the given region is available to the user account. 
I'll leave this issue open until the release if published, so you can get notified.

**Comment by fanaticalfishing** [comment]
Thank you for looking at it. I tried to put a node in South Africa but the cli refused. I have now modified aws.go and and compiled darknode-cli. I will use that to place a node in South Africa if AWS refuses to refund the savings plan I purchased.
