### ISSUE TITLE
How to login the darkNode Machine In digitalocean

### ISSUE THREAD

**Issue by Ultraman95** [renproject/darknode-cli#89]
I have created DarkNode on  digitalocean through “darknode up --name wonderreturn --do --do-token ******* ”；how to login the darkNode machine with ssh?

**Comment by tok-kkk** [comment]
You can use `darknode ssh DARKNODE-NAME` command to ssh into the darknode's machine

**Comment by Ultraman95** [comment]
can i use "ssh root@ip" command  to ssh into the darknode's machine?

**Comment by tok-kkk** [comment]
Yeah, you can. The `darknode ssh DARKNODE-NAME` command is using `ssh` command under the hood. You can also use `ssh` directly if you prefer. The username will be `darknode` instead of `root`. You'll also need to pass the key file which you can find in `~/.darknode/darknodes/DARKNODE-NAME/ssh_keypair`. Let me know if that works for you.

**Comment by Ultraman95** [comment]
pass the key file in ~/.darknode/darknodes/DARKNODE-NAME/ssh_keypair to where?
